# Generated by Django 5.2.9 on 2026-01-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='after_image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='before_image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_portfolio_grid',
            field=models.BooleanField(default=False),
        ),
    ]
