# Generated by Django 5.2.9 on 2026-01-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
        migrations.AddField(
            model_name='review',
            name='services',
            field=models.ManyToManyField(related_name='reviews', to='service.service'),
        ),
    ]
